<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class TargetMesin_model extends CI_Model
{

    public $table = 'tbl_target_mesin';
    public $id = 'id_targetMesin';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('bentuk', 'bentuk.id_bentuk = tbl_target_mesin.id_bentuk', 'left');

        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_targetMesin', $q);
        $this->db->or_like('id_bentuk', $q);
        $this->db->or_like('id_lembar', $q);
        $this->db->or_like('id_ukuran', $q);
        $this->db->or_like('id_speed_mesin', $q);
        $this->db->or_like('id_gsm', $q);
        $this->db->or_like('lebar_roll', $q);
        $this->db->or_like('panjang_pot', $q);
        $this->db->or_like('jml_gambar', $q);
        $this->db->or_like('kebutuhan_bahan', $q);
        $this->db->or_like('kg_perpack', $q);
        $this->db->or_like('jml_orang', $q);
        $this->db->or_like('targetMesin', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('tbl_target_mesin.id_targetMesin', $q);
        $this->db->or_like('tbl_target_mesin.id_bentuk', $q);
        $this->db->or_like('tbl_target_mesin.id_lembar', $q);
        $this->db->or_like('tbl_target_mesin.id_ukuran', $q);
        $this->db->or_like('tbl_target_mesin.id_speed_mesin', $q);
        $this->db->or_like('tbl_target_mesin.id_gsm', $q);
        $this->db->or_like('tbl_target_mesin.lebar_roll', $q);
        $this->db->or_like('tbl_target_mesin.panjang_pot', $q);
        $this->db->or_like('tbl_target_mesin.jml_gambar', $q);
        $this->db->or_like('tbl_target_mesin.kebutuhan_bahan', $q);
        $this->db->or_like('tbl_target_mesin.kg_perpack', $q);
        $this->db->or_like('tbl_target_mesin.jml_orang', $q);
        $this->db->or_like('tbl_target_mesin.targetMesin', $q);
        $this->db->join('bentuk', 'bentuk.id_bentuk = tbl_target_mesin.id_bentuk', 'left');
        $this->db->join('warna', 'warna.id_warna = tbl_target_mesin.id_warna', 'left');
        $this->db->join('lembar_pack', 'lembar_pack.id_lembar = tbl_target_mesin.id_lembar', 'left');
        $this->db->join('ukuran', 'ukuran.id_ukuran = tbl_target_mesin.id_ukuran', 'left');
        $this->db->join('speed_mesin', 'speed_mesin.id_speed_mesin = tbl_target_mesin.id_speed_mesin', 'left');
        $this->db->join('gsm', 'gsm.id_gsm = tbl_target_mesin.id_gsm', 'left');
        $this->db->join('pattern', 'pattern.id_pattern = tbl_target_mesin.id_pattern', 'left');
        $this->db->join('grade', 'grade.id_grade = tbl_target_mesin.id_grade', 'left');

        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file TargetMesin_model.php */
/* Location: ./application/models/TargetMesin_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-08-28 09:36:28 */
/* http://harviacode.com */