<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Target_mesin_model extends CI_Model
{

    public $table = 'target_mesin';
    public $id = 'id_target_mesin';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_target_mesin', $q);
        $this->db->or_like('id_bentuk', $q);
        $this->db->or_like('id_ukuran', $q);
        $this->db->or_like('id_lembar', $q);
        $this->db->or_like('id_speed_mesin', $q);
        $this->db->or_like('target_mesin', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('target_mesin.id_target_mesin', $q);
        $this->db->or_like('target_mesin.id_bentuk', $q);
        $this->db->or_like('target_mesin.id_ukuran', $q);
        $this->db->or_like('target_mesin.id_lembar', $q);
        $this->db->or_like('target_mesin.id_speed_mesin', $q);
        $this->db->or_like('target_mesin.target_mesin', $q);
        $this->db->join('bentuk', 'bentuk.id_bentuk = target_mesin.id_bentuk', 'left');
        $this->db->join('ukuran', 'ukuran.id_ukuran = target_mesin.id_ukuran', 'left');
        $this->db->join('lembar_pack', 'lembar_pack.id_lembar = target_mesin.id_lembar', 'left');
        $this->db->join('speed_mesin', 'speed_mesin.id_speed_mesin = target_mesin.id_speed_mesin', 'left');

        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Target_mesin_model.php */
/* Location: ./application/models/Target_mesin_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-09-18 06:06:16 */
/* http://harviacode.com */